### ISSUE TITLE
some variables in data removed automatically

### ISSUE THREAD

**Issue by sivanagendra123** [AutoViML/AutoViz#10] opened 2019-12-30 05:33 UTC
Hi,
I gave input csv contains 20 variables,while preprocessing it removed all important columns,may i know the reason?. 
note:-  removed columns contains fill data without null values

**Comment by AutoViML** [comment] 2019-12-30 13:03
Can you please upload your notebook to a Colab or a GitHub with the data
and send me a link to share it with me? That’s the only way I can trouble
shoot it. One quick way to know what’s wrong with your data is to do:

df.dtypes

See if there is at least one numeric column. Make sure all data have proper
data types. Make sure they are not all ID columns or variables with no
change.

If above fail to reveal a clue, please send me the link as I requested.
Thanks
Ram

**Comment by AutoViML** [comment] 2020-01-12 14:32
I am closing this issue since you have not responded. Assume that this is no longer an issue. If not, please respond back with sample data so I can reproduce your issue. Thanks.

**Closed as completed by AutoViML** 2020-01-12 14:32 UTC

**Comment by Eastkap** [comment] 2020-02-01 16:42
It's so frustrating when the code thinks variables are of low value and ignores them. There should be an option to set a threshold

**Comment by AutoViML** [comment] 2020-02-01 17:50
Hi EastKap:
Can you please give me an example where it does this to a dataset? I’ll be
happy to provide a threshold if needed. Can you share the dataset on a
Github link or a Colab link?
Thanks
Ram

**Comment by Eastkap** [comment] 2020-02-01 22:50
I've sent you an email, I think I rather share the data through there since it's a bit private. @AutoViML
